version: '3'
services:
  go-ride-details:
    environment:
      - GOOGLE_MAPS_API_KEY
    build: go-ride-details
  ruby-ride-price:
    build: ruby-ride-price
    depends_on:
      - go-ride-details
    ports:
      - "$RIDE_SERVICE_PORT:9000"
